version: '3.7'

services:
  # Traefik Service
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true" # Enable Traefik dashboard (remove in production)
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com" # Change this email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-certificates:/letsencrypt"
    networks:
      - traefik

  # Quartz Service
  quartz:
    image: ghcr.io/jackyzha0/quartz:latest
    container_name: quartz
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quartz.rule=Host(`your-domain.com`)" # Replace with your domain
      - "traefik.http.routers.quartz.entrypoints=web"
      - "traefik.http.routers.quartz.entrypoints=websecure"
      - "traefik.http.routers.quartz.tls=true"
      - "traefik.http.routers.quartz.tls.certresolver=myresolver"
    environment:
      - QUARTZ_BASE_URL=https://your-domain.com # Replace with your domain
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  traefik-certificates:
